### ISSUE TITLE
Setup TravisCI for continuous building and testing

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#1]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by vlado92** [comment]
I will need permissions to do this.
https://docs.travis-ci.com/user/deployment/azure-web-apps/
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
https://github.com/travis-ci-examples/node.js/blob/master/.travis.yml
(just links i will refer to when needed)

**Comment by THEjoezack** [comment]
Heya sorry, just looking at this now - I _think_ everything is approved and setup?

**Comment by vlado92** [comment]
Travis is not fully setup, but it will be (hopefully) by the end of the day.
Dockerization is over, i think, it just need to be tested on more than my laptop.

**Comment by vlado92** [comment]
This is solved in [pull request](https://github.com/codingblocks/podcast-app/pull/44).
