### ISSUE TITLE
Re-add linting for Cypress files

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#125]
Originally taken out because of problem with os.homeDir showing up in the tests.

See https://github.com/codingblocks/podcast-app/pull/122

**Comment by davefollett** [comment]
Maybe we could use this for the cypress section?

https://github.com/cypress-io/eslint-plugin-cypress

**Comment by vlado92** [comment]
This one I knocked out in last nights run. :man_dancing:
