### ISSUE TITLE
Add data attributes for "Search Result" & "PlayList" items

### ISSUE THREAD

**Issue by dance2die** [codingblocks/podcast-app#182]
## ✨ New feature description
This is to make E2E (end to end) testing with Cypress easier and more robust.

Add following data attributes
1. `data-item-type='search'` for Search Result Items
1. `data-item-type='playlist'` for PlayList Items.

## ➕ Additional context
Requested by @davefollett on Freedom Day!

![image](https://user-images.githubusercontent.com/8465237/42298042-a7f5d1e6-7fd1-11e8-96f8-99bc3b4fe662.png)

**Comment by davefollett** [comment]
Closed by merge #185
