### ISSUE TITLE
Search values that contain # do not work

### ISSUE THREAD

**Issue by davefollett** [codingblocks/podcast-app#201]
## 👣 Steps to reproduce
1. Searching for C# and it will search for C
1. Searching for #C does nothing, confused as an anchor tag?

Other special character or characters not allowed in URLs should be tested.

## 🔬 Expected behavior
1. Return results for C#
1. Return results for #C

### 🖥 Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version 67.0.3396.99

### 📱 Smartphone
 - Device: Pixel XL
 - OS: Android 8.1.0
 - Browser: Chrome
 - Version: 67.0.3396.87

**Comment by dance2die** [comment]
## ➕ Additional Context
Entering `.../search/c#` in the address bar still searches for `c` as shown below.
![firefox_2018-07-15_02-11-23](https://user-images.githubusercontent.com/8465237/42731115-a8e3f4c4-87d4-11e8-9ed9-eb9f3cf2fa73.png)

**Comment by dance2die** [comment]
### React Router path match of `:query` drops `#`.

![image](https://user-images.githubusercontent.com/8465237/42731361-3d5e4f92-87d9-11e8-9f93-a6b91114af0f.png)

### Source Code - [RoutedApp Line 19](https://github.com/codingblocks/podcast-app/blob/master/website-react/src/RoutedApp.js#L19).

![image](https://user-images.githubusercontent.com/8465237/42731367-64cb5476-87d9-11e8-85a4-5a39dd57b06f.png)

**Comment by Madsn** [comment]
So based on what I've seen/read so far, I think the least hacky solution might be changing the URL format to be something like qit.cloud/search?query=query_goes_here

Alternatively we would probably have to do some conversion anytime we alter/use the path, so what's in the URL would be search/C%23 (%23 == #), and what we show on the page would be C#. Also we need to consider what is being sent to Azure search, I'm guessing it should be %23 in place of #.

**Comment by davefollett** [comment]
ℹ️ Additional Information

Special Characters https://docs.microsoft.com/en-us/rest/api/searchservice/lucene-query-syntax-in-azure-search#escaping-special-characters

Unsafe and reserved URL characters https://docs.microsoft.com/en-us/rest/api/searchservice/lucene-query-syntax-in-azure-search#encoding-unsafe-and-reserved-characters-in-urls
