### ISSUE TITLE
Add BxJS podcast

### ISSUE THREAD

**Issue by davefollett** [codingblocks/podcast-app#208]
## ✨ New feature description
Add the following podcast:
* https://github.com/BuildingXwithJS/bxjs-weekly

**Comment by davefollett** [comment]
I emailed the podcast owner and he provided this URL to use:
* http://feeds.soundcloud.com/users/soundcloud:users:484724019/sounds.rss

**Comment by THEjoezack** [comment]
Eek, I forgot about this - I'm adding it now but the feed doesn't actually have any episodes in it yet.
