### ISSUE TITLE
Setup Docker image

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#24]
The docker image is mainly to facilitate local dev.

Primary objectives:
Spin up a web server (ideally with https)
Allow for easy config changes by mapping something in for config.js

**Comment by vlado92** [comment]
Is option to map changable things it in .env good approach? From there it is fairly easily changing it.

**Comment by vlado92** [comment]
This is solved in [pull request](https://github.com/codingblocks/podcast-app/pull/44).
