### ISSUE TITLE
Adjust the "fuzzy" ness of searching

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#51]
Example: "coding blocs"

**Comment by THEjoezack** [comment]
I'm not loving what I'm reading in the docs here, seems like fuzzy operates at the word level. Searches like "Progressive Web App" are returning results for "API", for example.

I'm going to leave it off for now and close this ticket, I will go ahead and leave in a change that makes it easier to resurrect it if we want to try again in the future.

https://docs.microsoft.com/en-us/rest/api/searchservice/lucene-query-syntax-in-azure-search#bkmk_fuzzy

**Comment by dance2die** [comment]
Yeah it doesn't look so great...
