### ISSUE TITLE
Searching for titles of show should emphasize the show

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#77]
For example, if you search "Coding Blocks" we should probably make sure that shows up prominently.

But this is tricky, if someone searches "JavaScript" do they want to see "JavaScript Jabber" or "State of JavaScript 2018" first?

Maybe we could prompt the user if we notice it's also in a podcast title?

**Comment by MadVikingGod** [comment]
I'm still a bit of a search noob, but could we have the show title effect the weight of an episode?

The other thing to think about is having tagged? searches, like Title:"Coding Blocks".

**Comment by THEjoezack** [comment]
Just added a scoring profile that exactly this: https://github.com/codingblocks/podcast-app/pull/242

It emphasizes episode title and "freshness", and de-emphasizes podcast title (but it is searched now)

Also, tagged searches already works...though we don't offer you any hint of how to do it :)

Example: https://qit.cloud/search/podcastTitle%3A%22Coding%20Blocks%22
