### ISSUE TITLE
Certain audioUrl files can't currently be proxied

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#86]
Examples of shows that can't be proxied with the currently strategy. It happens when there's a http url that redirects to another http url

    {
      "titleCleanser": "^\\d+:\\s",
      "url": "https://threedevsandamaybe.com/podcast.xml",
      "title": null,
      "forceHttps": false
    },
    {       “titleCleaners”: null,       “url”: “http://feeds.codenewbie.org/cnpodcast.xml”,
       “title”: “Code Newbie”,
       “forceHttps”: true
     },
    {
      "titleCleanser": null,
      "url": "http://feeds.feedburner.com/RunasRadio",
      "title": "Run As Radio",
      "forceHttps": false
    },

**Comment by Madsn** [comment]
I could take a look, see if I can resolve the issue with proxying redirecting urls. Please assign this to me :)

**Comment by Madsn** [comment]
Now that the shows that can't be proxied are removed - what can I use to verify that my change to the proxy works?

**Comment by Madsn** [comment]
Found an example of an episode that fails: Practical Test Driven Development with John Callaway and Clayton Hunt
